name: "EchoMind - AI Memory Layer"
description: "Personal Memory Layer for AI Applications with Home Assistant Integration. All memory remains local."
version: "1.0.0"
slug: "echomind"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8765/tcp: 8765 # EchoMind API
  3000/tcp: 3000 # Web UI Dashboard
ports_description:
  8765/tcp: "EchoMind API Endpoint"
  3000/tcp: "EchoMind Web UI Dashboard"
options:
  encryption_enabled: true
  local_only: true
  api_key: ""
  log_level: "info"
  max_memories: 10000
  cleanup_days: 30
schema:
  encryption_enabled: "bool"
  local_only: "bool"
  api_key: "str?" # Optional API key
  log_level: "list(trace|debug|info|notice|warning|error|fatal)" # Expanded log levels
  max_memories: "int(100,50000)"
  cleanup_days: "int(1,365)"
map:
  - "config:rw"
  - "ssl:ro"
  - "media:rw" # For potential future use (e.g., storing media related to memories)
  - "share:rw" # If you plan to allow access to /share for backups or other data
homeassistant_api: true # Needs access to Home Assistant API
hassio_api: true # Needs access to Supervisor API (e.g. for notifications, addon info)
# Potentially use hassio_role for more fine-grained permissions in the future
# hassio_role: default
image: "ghcr.io/mercuryin/echomind-ha-addon" # Placeholder, update with your actual image
