name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image for amd64
        uses: docker/build-push-action@v5
        with:
          context: ./echomind
          file: ./echomind/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.21
            BUILD_ARCH=amd64
            BUILD_VERSION=${{ steps.meta.outputs.version }}
          pull: true

      - name: Build and push Docker image for arm64
        uses: docker/build-push-action@v5
        with:
          context: ./echomind
          file: ./echomind/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-base:3.21
            BUILD_ARCH=aarch64
            BUILD_VERSION=${{ steps.meta.outputs.version }}
          pull: true

      - name: Build and push Docker image for armv7
        uses: docker/build-push-action@v5
        with:
          context: ./echomind
          file: ./echomind/Dockerfile
          push: true
          platforms: linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/armv7-base:3.21
            BUILD_ARCH=armv7
            BUILD_VERSION=${{ steps.meta.outputs.version }}
          pull: true 